version: "3.9"
services:
  postgres:
    container_name: foodate_db
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "foodate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_foodate
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "kheyfets"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device:  ./volumes/db_data
      o: bind
  pgadmin-data:
    driver: "local"
    driver_opts:
      type: none
      device:  ./volumes/pgadmin_data
      o: bind

networks:
  postgres:
    driver: bridge